version: '3.1'

services:
  www:
    container_name: gravpl_www
    image: outrigger/apache-php:php71
    network_mode: "bridge"
    environment:
      DOCROOT: /var/www
    volumes:
      - .:/var/www/
    labels:
      com.dnsdock.name: www
      com.dnsdock.image: gravpl
      outrigger.project: gravpl
