v: 2.6.0
overrideConfig: q
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
  - scripts
  - styles
cleanPublic: false
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: bolt-website
sourceDir: src
defaultPattern: 05-pages-bolt-homepage
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: >-
  {%([ ]+)?(?:include|extends|embed)(
  |\()[&quot;\&#039;]([\/.@A-Za-z0-9-]+)[&quot;\&#039;]([
  A-Za-z0-9-&\}_\n\{&quot;:\&#039;,\/. \[\]]+)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .md
plugins:
  twigNamespaces:
    enabled: true
    namespaces:
      bolt:
        paths:
          - src/_patterns/01-core/01-settings/settings-colors/demos
          - src/_patterns/01-core/01-settings/settings-colors/src/twig
          - src/_patterns/01-core/02-tools/tools-spacing/demos
          - src/_patterns/01-core/04-elements/elements-headings
          - src/_patterns/01-core/04-elements/elements-images
          - src/_patterns/01-core/04-elements/elements-links
          - src/_patterns/01-core/04-elements/elements-paragraphs
          - src/_patterns/01-core/04-elements/elements-small
          - src/_patterns/01-core/04-elements/elements-tables
          - src/_patterns/01-core/05-objects/01-lists/bolt-bare-list/src
          - src/_patterns/01-core/05-objects/01-lists/bolt-inline-list/src
          - src/_patterns/01-core/05-objects/01-lists/bolt-ui-list/src
          - src/_patterns/01-core/05-objects/02-layout/bolt-block/src
          - src/_patterns/01-core/05-objects/02-layout/bolt-flag/src
          - src/_patterns/01-core/05-objects/02-layout/bolt-grid
          - src/_patterns/01-core/05-objects/02-layout/bolt-island/src
          - src/_patterns/01-core/05-objects/02-layout/bolt-wrapper/src
          - src/_patterns/01-core/05-objects/03-display/bolt-crop/src
          - src/_patterns/01-core/05-objects/03-display/bolt-ratio/src
          - src/_patterns/02-components/bolt-action-block/lib
          - src/_patterns/02-components/bolt-action-block/src
          - src/_patterns/02-components/bolt-background/demo
          - src/_patterns/02-components/bolt-background/src
          - src/_patterns/02-components/bolt-band/demo
          - src/_patterns/02-components/bolt-band/src
          - src/_patterns/02-components/bolt-button-group/src
          - src/_patterns/02-components/bolt-button/demos
          - src/_patterns/02-components/bolt-button/src
          - src/_patterns/02-components/bolt-card/src
          - src/_patterns/02-components/bolt-chip-list
          - src/_patterns/02-components/bolt-chip/lib
          - src/_patterns/02-components/bolt-chip/src
          - src/_patterns/02-components/bolt-headline/demo
          - src/_patterns/02-components/bolt-headline/demo/h1-through-h6
          - src/_patterns/02-components/bolt-headline/src
          - src/_patterns/02-components/bolt-image
          - src/_patterns/02-components/bolt-image/src
          - src/_patterns/02-components/bolt-link
          - src/_patterns/02-components/bolt-logo/src
          - src/_patterns/02-components/bolt-page-footer/lib
          - src/_patterns/02-components/bolt-page-footer/src
          - src/_patterns/02-components/bolt-quote
          - src/_patterns/02-components/bolt-teaser/src/twig
          - src/_patterns/02-components/components-card/lib
          - src/_patterns/03-templates/templates-default
          - src/_patterns/04-pages
