v: 2.6.0
regenerateStyleguideKit: 'true'
overrideConfig: false
ie:
    - DS_Store
    - less
    - scss
    - html
    - js
id:
    - scss
    - .svn
    - .sass-cache
    - scripts
    - styles
    - splash-screen.html
    - assets
cleanPublic: false
patternStates:
    - inprogress
    - inreview
    - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
publicDir: ../../www/pattern-lab/ja
sourceDir: ../pattern-lab/src
defaultPattern: viewall-components-all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishViewportRange:
    s:
        - 320
        - 600
    m:
        - 600
        - 1000
    l:
        - 1000
        - 2600
ishControlsHide:
    - hay
    - disco
    - random
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: >-
  {%([ ]+)?(?:include|extends|embed)(
  |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}
lineageMatchKey: 3
patternExtension: twig
twigExtensions:
    - '\PatternLab\DrupalTwigExtensions\Basic'
    - '\BasaltInc\TwigTools\TwigExtensions\BasaltFakerExtension'
    - '\Bolt\TwigExtensions\BoltCore'
    - '\Bolt\TwigExtensions\BoltExtras'
twigDebug: true
twigAutoescape: false
# twigDefaultDateFormat: ''
# twigDefaultIntervalFormat: ''
# twigMacroExt: macro.twig
# twigFilterExt: filter.php
# twigFunctionExt: function.php
# twigTagExt: tag.php
# twigTestExt: test.php
plugins:
  twigNamespaces:
    enabled: true
    readFromFile: ../../www/pattern-lab/ja/build/data/twig-namespaces.bolt.json
